import {initial,boards,locate,eligible,trace,moves,play,pass,score} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('space'),ctx=canvas.getContext('2d');
const letters=['α','β','γ','δ','ε','ζ','η','θ','ι','κ','λ','μ'];const world=l=>letters[l]||String(l+1),coord=(i)=>String.fromCharCode(65+i%state.n)+(Math.floor(i/state.n)+1);
const B=224,P=9,COL=292,ROW=305;
let state=initial(),committed=state,stages=[],allMoves=[],moveMap=new Map(),nodeList=[],selected={l:0,t:0},hover=null,lastPath=null,onlyHeads=false,worker=null,thinking=null,aiStats='',status='点のあるマスに着手すると仮置きします。',frame=0;
let aiTimer=null,searchEpoch=0;let mode='cpu',human=1,difficulty='strong',camera={x:0,y:0,z:1.4},cw=0,ch=0,drag=null,pointers=new Map(),pinch=null,keyboardCell=0;
const key=(l,t)=>l+':'+t;const pos=(l,t)=>({x:t*COL,y:l*ROW});
function canAct(){return !state.ended&&!thinking&&state.p===committed.p&&(mode==='local'||committed.p===human);}
function canUndo(){return stages.length>0&&!thinking&&!committed.ended&&(mode==='local'||committed.p===human);}
function canSubmit(){return stages.length>0&&(state.ended||state.p!==committed.p);}
function resize(){let r=canvas.getBoundingClientRect();cw=r.width;ch=r.height;let d=Math.min(devicePixelRatio||1,2);canvas.width=cw*d;canvas.height=ch*d;ctx.setTransform(d,0,0,d,0,0);requestDraw();}
function requestDraw(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;draw();});}
function rounded(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function line(points,color,width=2,arrow=false){if(points.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let p of points.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();if(arrow){let p=points.at(-1),q=points.at(-2),a=Math.atan2(p.y-q.y,p.x-q.x),z=8;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-z*Math.cos(a-.5),p.y-z*Math.sin(a-.5));ctx.lineTo(p.x-z*Math.cos(a+.5),p.y-z*Math.sin(a+.5));ctx.closePath();ctx.fill();}}
function centerCell(l,t,i){let a=locate(state,l,t),node=nodeList.find(n=>n.l===l&&n.t===t);if(!node&&a){l=a.l;t=a.t;node=nodeList.find(n=>n.l===l&&n.t===t);}if(!node)return null;let p=pos(l,t),c=(B-P*2)/state.n;return{x:p.x+P+(i%state.n+.5)*c,y:p.y+P+(Math.floor(i/state.n)+.5)*c};}
function draw(){ctx.clearRect(0,0,cw,ch);ctx.fillStyle='#e9ece8';ctx.fillRect(0,0,cw,ch);ctx.strokeStyle='#dce2d9';ctx.lineWidth=1;let step=44*camera.z;if(step>12){let ox=((camera.x%step)+step)%step,oy=((camera.y%step)+step)%step;ctx.beginPath();for(let x=ox;x<cw;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,ch);}for(let y=oy;y<ch;y+=step){ctx.moveTo(0,y);ctx.lineTo(cw,y);}ctx.stroke();}
ctx.save();ctx.translate(camera.x,camera.y);ctx.scale(camera.z,camera.z);let activePath=hover||lastPath,related=new Set();if(activePath){related.add(key(activePath.l,activePath.t));for(let r of activePath.tr.rays){for(let c of [...r.cells,r.anchor]){let at=locate(state,c.viewL??c.l,c.t);if(at)related.add(key(at.l,at.t));}}}let visible=nodeList.filter(n=>!onlyHeads||n.head||related.has(key(n.l,n.t)));
// Shared timeline backbone. Every branch starts at its actual source time.
for(let w of state.worlds){let y=w.id*ROW+B/2,x0=w.start*COL-18,x1=w.head*COL+B+44;ctx.globalAlpha=.42;ctx.strokeStyle='#9b80b9';ctx.lineWidth=15;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x0,y);ctx.lineTo(x1,y);ctx.stroke();ctx.globalAlpha=1;line([{x:x1-12,y},{x:x1+5,y}], '#9b80b9',5,true);if(w.parent!==null&&!onlyHeads){let p=pos(w.parent,w.origin),end=pos(w.id,w.start);ctx.strokeStyle='#9b80b9';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(p.x+B,p.y+B/2);ctx.bezierCurveTo(p.x+B+44,p.y+B/2,end.x-40,end.y+B/2,end.x,end.y+B/2);ctx.stroke();}}
let px=state.t*COL+B/2;ctx.strokeStyle='#9d7fbd';ctx.setLineDash([5,6]);ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(px,-70);ctx.lineTo(px,(state.worlds.length-1)*ROW+B+40);ctx.stroke();ctx.setLineDash([]);ctx.font=Math.max(12,12/camera.z)+'px system-ui';ctx.textAlign='center';ctx.fillStyle='#755493';ctx.fillText('PRESENT · T '+state.t,px,-50);
for(let n of visible){let p=pos(n.l,n.t),sx=p.x*camera.z+camera.x,sy=p.y*camera.z+camera.y;if(sx+B*camera.z<0||sx>cw||sy+B*camera.z<-50||sy>ch)continue;drawBoard(n,p);}
let path=hover||lastPath;if(path?.tr?.rays.length){let start=centerCell(path.l,path.t,path.i);if(start){for(let ray of path.tr.rays){let pts=[start,...ray.cells.map(c=>centerCell(c.viewL??c.l,c.t,c.i)),centerCell(ray.anchor.l,ray.anchor.t,ray.anchor.i)].filter(Boolean);if(pts.length<2)continue;ctx.globalAlpha=.9;line(pts,ray.dir[2]||ray.dir[3]?'#edccff':'#f1f8c9',2.8,true);for(let c of ray.cells){let cp=centerCell(c.viewL??c.l,c.t,c.i);if(cp){ctx.strokeStyle='#f7d591';ctx.lineWidth=2;ctx.beginPath();ctx.arc(cp.x,cp.y,(B-P*2)/state.n*.43,0,Math.PI*2);ctx.stroke();}}}ctx.globalAlpha=1;ctx.fillStyle='#f5d888';ctx.beginPath();ctx.arc(start.x,start.y,4.5,0,Math.PI*2);ctx.fill();}}
ctx.restore();$('zoomText').textContent=Math.round(camera.z*100)+'%';}
function drawBoard(n,p){let active=n.head,sel=selected.l===n.l&&selected.t===n.t,allowed=canAct()&&eligible(state,n.l,n.t),sq=(B-P*2)/state.n;ctx.lineWidth=sel?2.5:1;ctx.shadowColor='#23372828';ctx.shadowBlur=active?13:5;ctx.shadowOffsetY=active?7:3;rounded(p.x-3,p.y-3,B+6,B+6,6,active?'#f9fbef':'#c4d0c2',sel?'#9372b4':active?'#f9fbef':'#abb9ac');ctx.shadowBlur=0;ctx.shadowOffsetY=0;rounded(p.x,p.y,B,B,3,active?'#294737':'#55735d');
ctx.font=Math.max(11,11/camera.z)+'px system-ui';ctx.textAlign='left';ctx.fillStyle='#34483b';ctx.fillText((camera.z>.65?'世界線 ':'')+world(n.l),p.x,p.y-13);ctx.textAlign='right';ctx.fillStyle=n.t===state.t?'#775399':'#718072';ctx.fillText('T '+String(n.t).padStart(2,'0')+(n.virtual?'  −':active?'  ●':''),p.x+B,p.y-13);
for(let i=0;i<state.n*state.n;i++){let x=p.x+P+i%state.n*sq,y=p.y+P+Math.floor(i/state.n)*sq,v=n.b[i],m=moveMap.get(key(n.l,n.t)+':'+i);ctx.fillStyle=((i%state.n+Math.floor(i/state.n))%2===0)?(active?'#47795c':'#739279'):(active?'#528566':'#7c9c80');ctx.fillRect(x,y,sq+.1,sq+.1);if(v){let cx=x+sq/2,cy=y+sq/2,r=sq*.37;ctx.shadowColor='#10271970';ctx.shadowBlur=2;ctx.shadowOffsetY=2;let g=ctx.createRadialGradient(cx-r*.35,cy-r*.4,r*.1,cx,cy,r);if(v===1){g.addColorStop(0,'#566157');g.addColorStop(.7,'#202b24');g.addColorStop(1,'#152018');}else{g.addColorStop(0,'#fffff5');g.addColorStop(.8,'#edeedf');g.addColorStop(1,'#c8cebb');}ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;}else if(m&&allowed){let cross=m.f.some(c=>c.cross);ctx.fillStyle=cross?'#d5b3f3':'#d3ebbe';ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(x+sq/2,y+sq/2,sq*.105,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=cross?'#d5b3f3':'#d3ebbe';ctx.lineWidth=.7;ctx.beginPath();ctx.arc(x+sq/2,y+sq/2,sq*.18,0,Math.PI*2);ctx.stroke();}}
let last=state.log[0];if(last&&!last.pass&&last.l===n.l&&last.t+1===n.t){let cp=centerCell(n.l,n.t,last.i);if(cp){ctx.fillStyle='#d4b6f0';ctx.beginPath();ctx.arc(cp.x,cp.y,2,0,Math.PI*2);ctx.fill();}}
if(active){ctx.font=Math.max(10,10/camera.z)+'px system-ui';ctx.textAlign='left';ctx.fillStyle=n.t===state.t?'#71518e':'#65766a';ctx.fillText(n.virtual?'待機 · 記録対象外':n.t===state.t?'現在 · '+(state.p===1?'黒':'白'):'先端',p.x,p.y+B+19);}
}
function fit(which='all'){let list=which==='current'?nodeList.filter(n=>n.head&&n.t===state.t):nodeList.filter(n=>!onlyHeads||n.head);if(!list.length)return;let left=Math.min(...list.map(n=>n.t*COL)),right=Math.max(...list.map(n=>n.t*COL+B)),top=Math.min(...list.map(n=>n.l*ROW))-35,bottom=Math.max(...list.map(n=>n.l*ROW+B))+30;let mobile=cw<700,availW=cw-(mobile?40:300),availH=ch-(mobile?280:190),z=Math.max(.075,Math.min(which==='current'?2.1:1.5,availW/(right-left+70),availH/(bottom-top+45)));camera={z,x:20+(availW-(right-left)*z)/2-left*z,y:105+(availH-(bottom-top)*z)/2-top*z};requestDraw();}
function focusNode(l,t){let mobile=cw<700,z=Math.min(mobile?1.22:1.65,(cw-(mobile?40:310))/B,(ch-(mobile?295:180))/B);z=Math.max(.4,z);let p=pos(l,t),aw=cw-(mobile?20:280);camera={z,x:aw/2-(p.x+B/2)*z,y:90+(ch-(mobile?285:180))/2-(p.y+B/2)*z};requestDraw();}
function refresh(){nodeList=boards(state);allMoves=state.ended?[]:moves(state);moveMap=new Map(allMoves.map(m=>[key(m.l,m.t)+':'+m.i,m]));if(!nodeList.some(n=>n.l===selected.l&&n.t===selected.t)){let n=nodeList.find(n=>n.head&&n.t===state.t)||nodeList.at(-1);selected={l:n.l,t:n.t};}let sc=score(state);$('scoreBlack').textContent=sc[1];$('scoreWhite').textContent=sc[-1];$('boardCount').textContent=nodeList.filter(n=>!n.virtual).length+' 盤';$('remaining').textContent=state.limit-state.placed;$('turnDisc').className='disc '+(committed.p===1?'black':'white');document.body.classList.toggle('thinking',!!thinking);$('turnText').textContent=state.ended?(stages.length?'終局の仮置き':'対局終了'):thinking==='ai'?'CPUが思考中':thinking==='hint'?'ヒントを探索中':(committed.p===1?'黒':'白')+'の手番'+(stages.length?' · '+stages.length+'手を仮置き':'');$('status').textContent=status;$('submit').disabled=!canSubmit()||!!thinking;$('submit').innerHTML=canSubmit()?'手番を確定 <span>↵</span>':stages.length?'現在の盤面へ続けて着手':'手番を確定 <span>↵</span>';$('undo').disabled=!canUndo();$('hint').disabled=!canAct();$('pass').classList.toggle('available',canAct()&&!allMoves.length);$('pass').disabled=!canAct()||!!allMoves.length;$('boardPicker').innerHTML=nodeList.map(n=>`<option value="${n.l}:${n.t}" ${selected.l===n.l&&selected.t===n.t?'selected':''}>${world(n.l)} / T ${n.t}${n.head?' · 先端':''}${n.virtual?' · 待機':''}</option>`).join('');$('selectionTitle').textContent='世界線 '+world(selected.l);$('selectionInfo').textContent='T '+String(selected.t).padStart(2,'0')+(selected.t===state.worlds[selected.l].head?' · 先端':' · 過去')+(state.worlds[selected.l].waits?.[selected.t]?' · 待機':'');$('log').innerHTML=state.log.slice(0,12).map(m=>`<p>${m.p===1?'黒':'白'} · ${m.pass?'パス':world(m.l)+' / T '+m.t+' → '+(m.t+1)+' · '+coord(m.i)+' / '+m.count+'枚'+(m.travel?' · 分岐':'')}</p>`).join('')||'<p>まだ着手はありません。</p>';requestDraw();}
function inspect(l,t,i){let m=moveMap.get(key(l,t)+':'+i);if(!m||!canAct()){hover=null;requestDraw();return;}let tr=trace(state,l,t,i);hover={l,t,i,tr};let spatial=tr.rays.filter(r=>!r.dir[2]&&!r.dir[3]).length,temporal=tr.rays.filter(r=>r.dir[3]).length,parallel=tr.rays.filter(r=>r.dir[2]).length;$('inspection').innerHTML=`<strong>${tr.flips.length}<small style="font-size:13px"> 枚を反転</small></strong>${world(l)} / T ${t} · ${coord(i)}${m.travel?' → 新しい世界線':''}<br>盤内 ${spatial}方向 · 時間 ${temporal} · 世界 ${parallel}`;requestDraw();}
function stage(l,t,i){if(!canAct())return;try{let tr=trace(state,l,t,i),next=play(state,l,i,t);stages.push(state);lastPath={l,t,i,tr};state=next;hover=null;let last=state.log[0];selected={l:last.l,t:last.t+1};$('welcome').hidden=true;status=canSubmit()?'仮置きを確認して「手番を確定」。戻すこともできます。':'現在線に残っている盤面へ、続けて着手してください。';refresh();let pp=pos(selected.l,selected.t),sx=pp.x*camera.z+camera.x,sy=pp.y*camera.z+camera.y;if(sx<0||sx+B*camera.z>cw-(cw<700?0:230)||sy<75||sy+B*camera.z>ch-120)focusNode(selected.l,selected.t);if($('boardDialog').open)$('boardDialog').close();}catch(e){status=e.message;refresh();}}
function finishTurn(){committed=state;stages=[];lastPath=null;hover=null;status='現在線の盤面、または同じ手番の過去へ着手できます。';refresh();if(state.ended){showResult();return;}if(mode==='cpu'&&state.p!==human)startAI();else fit('current');}
function submit(){if(!canSubmit()||thinking)return;finishTurn();}
function showResult(){let sc=score(state);$('resultTitle').textContent=sc[1]===sc[-1]?'引き分け':sc[1]>sc[-1]?'黒の勝利':'白の勝利';$('resultScore').textContent='BLACK '+sc[1]+' : '+sc[-1]+' WHITE';if(!$('result').open)$('result').showModal();}
function stopWorker(){searchEpoch++;clearTimeout(aiTimer);aiTimer=null;worker?.terminate();worker=null;thinking=null;}
function askSearch(kind,done){stopWorker();const epoch=searchEpoch,snapshot=state;let settled=false;const current=()=>epoch===searchEpoch&&state===snapshot;const complete=r=>{if(!current()||settled)return;settled=true;stopWorker();done(r);};thinking=kind;status=kind==='ai'?'応手と時間分岐を検討しています。':'先読みで候補を比較しています。';refresh();let options={budget:difficulty==='strong'?2800:1000,width:difficulty==='strong'?8:5,maxDepth:5};try{worker=new Worker(new URL('./worker.mjs',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(!current()||settled)return;if(data.type==='progress'){aiStats=`${data.depth}手先 / ${data.nodes}局面`;status=(kind==='ai'?'CPU':'ヒント')+'：'+aiStats+'を探索';$('status').textContent=status;}else if(data.type==='done'){complete(data);}else if(data.type==='error'){worker?.terminate();worker=null;fallback();}};worker.onerror=()=>{if(!current()||settled)return;worker?.terminate();worker=null;fallback();};worker.postMessage({state:snapshot,options});}catch{fallback();}
async function fallback(){if(!current()||settled)return;thinking=kind;try{let {search}=await import('./search.mjs');if(!current()||settled)return;let r=search(snapshot,{budget:400,width:4,maxDepth:3});complete(r);}catch(e){if(!current()||settled)return;stopWorker();status='探索エラー：'+e.message;refresh();}}
}
function startAI(){if(thinking||state.ended||state.placed>=state.limit||mode!=='cpu'||state.p===human)return;askSearch('ai',r=>{try{let prior=state;if(r.move){let m=r.move;lastPath={l:m.l,t:m.t,i:m.i,tr:trace(state,m.l,m.t,m.i)};state=play(state,m.l,m.i,m.t);selected={l:state.log[0].l,t:state.log[0].t+1};}else state=pass(state);stages.push(prior);status=`CPU：${r.depth}手先・${r.nodes}局面を検討`;refresh();if(state.ended||state.p!==committed.p){committed=state;stages=[];lastPath=null;refresh();if(state.ended)showResult();else fit('current');}else{const epoch=searchEpoch;aiTimer=setTimeout(()=>{if(epoch===searchEpoch)startAI();},180);}}catch(e){status=e.message;refresh();}});}
function undo(){if(!canUndo())return;state=stages.pop();hover=null;lastPath=null;status='直前の仮置きを取り消しました。確定済みの手番は戻せません。';refresh();fit('current');}
function largeBoard(){let b=locate(state,selected.l,selected.t);if(!b)return;$('largeTitle').textContent='世界線 '+world(selected.l)+' / T '+selected.t;$('largeBoard').style.gridTemplateColumns=`repeat(${state.n},1fr)`;$('largeBoard').innerHTML=b.b.map((v,i)=>{let legal=moveMap.has(key(selected.l,selected.t)+':'+i)&&canAct();return `<button class="large-cell" data-i="${i}" ${legal?'':'disabled'} aria-label="${coord(i)} ${v===1?'黒':v===-1?'白':legal?'合法手':'空き'}">${v?'<i class="disc '+(v===1?'black':'white')+'"></i>':legal?'<i class="legal"></i>':''}</button>`;}).join('');$('largeBoard').querySelectorAll('button').forEach(el=>{el.onclick=()=>stage(selected.l,selected.t,+el.dataset.i);el.onfocus=()=>inspect(selected.l,selected.t,+el.dataset.i);});$('largeNote').textContent=eligible(state,selected.l,selected.t)?'点のあるマスを選ぶと仮置きします。':'観測中。この時刻は現在の手番では着手できません。';if(!$('boardDialog').open)$('boardDialog').showModal();}
function hit(x,y){let wx=(x-camera.x)/camera.z,wy=(y-camera.y)/camera.z;for(let n of nodeList){if(onlyHeads&&!n.head)continue;let p=pos(n.l,n.t);if(wx>=p.x&&wx<p.x+B&&wy>=p.y&&wy<p.y+B){let cx=Math.floor((wx-p.x-P)/((B-P*2)/state.n)),cy=Math.floor((wy-p.y-P)/((B-P*2)/state.n));return{l:n.l,t:n.t,i:cx>=0&&cy>=0&&cx<state.n&&cy<state.n?cy*state.n+cx:-1};}}return null;}
function zoom(f,x=cw/2,y=ch/2){let z=Math.max(.07,Math.min(3,camera.z*f)),wx=(x-camera.x)/camera.z,wy=(y-camera.y)/camera.z;camera={z,x:x-wx*z,y:y-wy*z};requestDraw();}
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.0012),e.offsetX,e.offsetY);},{passive:false});
canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});if(pointers.size===2){let a=[...pointers.values()];pinch={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)};drag=null;}else drag={x:e.offsetX,y:e.offsetY,ox:camera.x,oy:camera.y,moved:false};};
canvas.onpointermove=e=>{if(pointers.has(e.pointerId)){pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});if(pointers.size===2&&pinch){let a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);zoom(d/Math.max(1,pinch.d),(a[0].x+a[1].x)/2,(a[0].y+a[1].y)/2);pinch.d=d;return;}if(drag){let dx=e.offsetX-drag.x,dy=e.offsetY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;if(drag.moved){camera.x=drag.ox+dx;camera.y=drag.oy+dy;hover=null;requestDraw();}return;}}let h=hit(e.offsetX,e.offsetY);canvas.style.cursor=h&&moveMap.has(key(h.l,h.t)+':'+h.i)&&canAct()?'pointer':'grab';if(h&&h.i>=0)inspect(h.l,h.t,h.i);else if(hover){hover=null;requestDraw();}};
canvas.onpointerup=e=>{let d=drag;let wasPinch=!!pinch;pointers.delete(e.pointerId);if(pointers.size<2)pinch=null;drag=null;if(!wasPinch&&d&&!d.moved){let h=hit(e.offsetX,e.offsetY);if(h){selected={l:h.l,t:h.t};keyboardCell=Math.max(0,h.i);if(moveMap.has(key(h.l,h.t)+':'+h.i)&&canAct())stage(h.l,h.t,h.i);else{refresh();status='選択した盤面を右の「拡大」から詳しく見られます。';$('status').textContent=status;}}}};canvas.onpointercancel=()=>{pointers.clear();drag=null;pinch=null;};canvas.onpointerleave=()=>{if(!drag){hover=null;requestDraw();}};
canvas.onkeydown=e=>{let handled=true;if(e.key==='ArrowRight')keyboardCell=(keyboardCell+1)%(state.n*state.n);else if(e.key==='ArrowLeft')keyboardCell=(keyboardCell+state.n*state.n-1)%(state.n*state.n);else if(e.key==='ArrowDown')keyboardCell=(keyboardCell+state.n)%(state.n*state.n);else if(e.key==='ArrowUp')keyboardCell=(keyboardCell+state.n*state.n-state.n)%(state.n*state.n);else if(e.key==='Enter'){if(e.ctrlKey||e.metaKey)submit();else stage(selected.l,selected.t,keyboardCell);}else if(e.key==='['||e.key===']'){let ix=nodeList.findIndex(n=>n.l===selected.l&&n.t===selected.t),n=nodeList[(ix+(e.key===']'?1:nodeList.length-1))%nodeList.length];selected={l:n.l,t:n.t};refresh();focusNode(n.l,n.t);}else if(e.key==='Escape'){hover=null;lastPath=null;requestDraw();}else handled=false;if(handled){e.preventDefault();inspect(selected.l,selected.t,keyboardCell);}};
$('submit').onclick=submit;$('undo').onclick=undo;$('pass').onclick=()=>{try{let q=pass(state);stages.push(state);state=q;status='パスを仮置きしました。手番を確定してください。';refresh();}catch(e){status=e.message;refresh();}};
$('hint').onclick=()=>{if(!canAct())return;askSearch('hint',r=>{status=r.move?`${world(r.move.l)} / T ${r.move.t} の ${coord(r.move.i)} を推奨（${r.depth}手先を検討）。`:'合法手がありません。パスしてください。';refresh();if(r.move){selected={l:r.move.l,t:r.move.t};refresh();focusNode(selected.l,selected.t);inspect(r.move.l,r.move.t,r.move.i);}});};
$('allView').onclick=()=>{onlyHeads=false;$('allView').classList.add('active');$('nowView').classList.remove('active');fit();};$('nowView').onclick=()=>{onlyHeads=true;$('nowView').classList.add('active');$('allView').classList.remove('active');hover=null;lastPath=null;fit();};$('fit').onclick=()=>fit();$('focus').onclick=()=>fit('current');$('zoomIn').onclick=()=>zoom(1.25);$('zoomOut').onclick=()=>zoom(.8);$('boardPicker').onchange=()=>{let [l,t]=$('boardPicker').value.split(':').map(Number);selected={l,t};onlyHeads=false;$('allView').classList.add('active');$('nowView').classList.remove('active');refresh();focusNode(l,t);};$('boardDialogBtn').onclick=largeBoard;$('collapse').onclick=()=>{let v=$('inspectorBody').hidden;$('inspectorBody').hidden=!v;$('collapse').textContent=v?'−':'＋';document.querySelector('.inspector').classList.toggle('collapsed',!v);};$('rulesBtn').onclick=()=>$('rules').showModal();$('newBtn').onclick=()=>$('setup').showModal();$('again').onclick=()=>{$('result').close();$('setup').showModal();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('dismissWelcome').onclick=()=>{$('welcome').hidden=true;};
$('start').onclick=()=>{stopWorker();state=initial(+$('size').value);committed=state;stages=[];selected={l:0,t:0};hover=null;lastPath=null;mode=$('mode').value;human=+$('humanColor').value;difficulty=$('difficulty').value;status='点のあるマスへ着手。仮置き後に手番を確定します。';$('setup').close();refresh();fit('current');if(mode==='cpu'&&human===-1)startAI();};
window.addEventListener('resize',()=>{resize();});resize();refresh();fit('current');if(cw<700){$('inspectorBody').hidden=true;document.querySelector('.inspector').classList.add('collapsed');$('collapse').textContent='＋';}
